<?php
/**
 * Created by PhpStorm.
 * User: 李沈阳
 * Date: 2018/1/10
 * Time: 14:38
 */

namespace app\admin\controller;

use app\common\model\About as AboutModel;

/**
 * Class About
 * @package app\admin\controller
 * 关于我们控制器
 */
class About extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $this->assign('data', AboutModel::find());  //
        return $this->fetch();
    }


    public function doEdit()
    {
        if( $this->request->isPost() )
        {
            $data = AboutModel::get(input('post.id'));
            if(!$data)
            {
                $arr['content'] = input('post.content');
                $result = AboutModel::create($arr);
                return $this->resultHandle($result);
            }
            $data->content = input('post.content');
            $result = $data->save();
            return $this->resultHandle($result);
        }
        else{
            $this->assign('data', AboutModel::find());
            return $this->fetch();
        }
    }
}