<?php
/**
 * Created by PhpStorm.
 * User: 李沈阳
 * Date: 2018/1/2
 * Time: 18:41
 */

namespace app\admin\controller;


use think\Db;

class Index extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index()
    {
        return $this->fetch();
    }

    //加载欢迎界面
    public function  welcome(){
        $server=[
            'HTTP_HOST'=>$_SERVER['HTTP_HOST'],
            'SERVER_SOFTWARE'=>$_SERVER['SERVER_SOFTWARE'],
            'osname'=>php_uname(),
            'HTTP_ACCEPT_LANGUAGE'=>$_SERVER['HTTP_ACCEPT_LANGUAGE'],
            'SERVER_PORT'=>$_SERVER['SERVER_PORT'],
            'SERVER_NAME'=>$_SERVER['SERVER_NAME'],
        ];
        $version=Db::query("select version()");
        $server['mysqlversion']=$version[0]['version()'];
        $server['databasename'] =config('database')['database'];
        $server['phpversion']=phpversion();
        $server['maxupload']=ini_get('max_file_uploads');
        $this->assign('service',$server);
        return view();
    }

}