<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/9/20
 * Time: 11:28
 */

namespace app\admin\controller;


use app\common\model\MemberLog;

class Log extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }



    public function toList(){
        $page = MemberLog::getLogPageList();

        $this->assign('page',$page);

        return $this->fetch();
    }
}