<?php
/**
 * Created by PhpStorm.
 * User: 李沈阳
 * Date: 2017/11/30
 * Time: 9:07
 */

namespace app\common\controller;


use think\Controller;
use think\Request;

class Common extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('mName', $this->request->module());
        $this->assign('cName', $this->request->controller());
        $this->assign('aName', $this->request->action());
        $this->assign('menu',config('menu'));
        $this->assign('kx',config('kx'));
    }



}