language: node_js
node_js:
- '4'
cache:
  directories:
  - node_modules
  - bower_components
install:
- npm install
- bower install
script:
- make build
deploy:
  provider: npm
  email: sdk@qiniu.com
  api_key:
    secure: d06l6wsuv/YFeY3E0TRGemGjtQ7LZdN9WxiFnseT2exTFkDgMw9EV2uOUWllXNrbxXUY+2ZpDswtYrgZ4exQGfKKQRGFy6/g8oxPgyylVwBz98vlie8NvXXmANoyt7mwQwjninf5/XUiY3cwn9YCaU1jyxcayFdQTex05T++qvc=
  on:
    tags: true
