<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/20
 * Time: 10:02
 */

namespace app\api\controller\v1;


use app\common\model\PartnerUserEum;
use app\common\model\UserNotices;
use app\lib\exception\NoticeException;
use enum\PartnerUserStatus;
use think\Db;


/**
 * Class Notice
 * @package app\api\controller\v1
 *
 * 用户消息控制器
 */
class Notice extends Base
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    protected $beforeActionList = [
        //验证登陆
        'checkLogin' => [ 'only' => 'noticeList,partnerUserEnm' ],
        //验证id参数必须
        'checkIDMustBePositiveInt' => [ 'only' => '' ],
        'checkUserScope' => [ 'only'=> 'partnerUserEnm'],

    ];

    //消息
    public function noticeList()
    {
        $limit = $this->getLimit();

        $wl = UserNotices::getPage(['user_id'=> $this->user['ud_id'], 'type'=> 2],$limit);
        $tz = UserNotices::getPage(['user_id'=> $this->user['ud_id'], 'type'=> 1],$limit);
        if( $wl->isEmpty() && $tz->isEmpty())
        {
            throw new NoticeException();
        }

        return show(true, 'ok', [
            'wl'=> $wl,
            'tz'=> $tz
        ]);
    }


    //需要用户确认消息
    public function partnerUserEnm()
    {
//          return $this->user['ud_id'];
//          $notice = Db::table('partner_user_eum')->where(['user_id'=> $this->user])->paginate(10);
        $notice = PartnerUserEum::getPage(['pue.user_id'=> $this->user['ud_id'] ]);
        return show(true, 'ok', $notice) ;
    }



}