<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/19
 * Time: 16:40
 */

namespace app\api\controller\v1;


use app\common\model\PartnerUser;
use enum\PartnerUserStatus;

class Phone extends Base
{




    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    protected $beforeActionList = [
        //前置操作，验证用户权限，必须是合伙才有权限访问
        'checkPartner' => ['only'=> ''],
        //前置操作 必须是用户才能访问
        'checkUserScope'=> [ 'only'=> 'userCallPhone' ],
        //必须登录情况下访问
        'checkLogin' => [ 'only'=> '']
    ];


    //用户打电话动作
    public function userCallPhone()
    {
        $userId = $this->user['ud_id'];
        $partnerId = input('phone');

        //查询是否是绑定关系
        $partnerUser = PartnerUser::get([ 'pu_partner_id'=> $partnerId, 'pu_user_id'=> $userId]);
        if( !$partnerUser )
        {
            $data = [
                'pu_partner_id'=> $partnerId,
                'pu_user_id'=> $userId,
                'source'=> '电话咨询'
            ];
            PartnerUser::create($data);
        }
        return show(true, 'ok', []);
    }


}