<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/19
 * Time: 14:28
 */

namespace app\api\controller\v1;

use app\common\model\BuildingColumn;
use app\common\model\BuildingDetails;
use app\common\model\Sort as SortModel;
use app\common\validate\IDMustBePositiveInt;
use think\Db;

/**
 * Class Sort
 * @package app\api\controller\v1
 * 建材分类控制器
 */
class Sort extends Base
{



    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }





    //获取一级分类
    public function getOneSort()
    {
        $one_sort = Db::table('building_column')->where([ 'pid'=> 0])->order(['order'=>'asc'])->select();
        $two_sort = Db::table('building_column')->where([ 'pid'=> $one_sort[0]['id']])->order(['order'=>'asc'])->select();//获取二级分类
        $buildings = BuildingDetails::getBuildingPage([ 'g_columr'=>$two_sort[0]['id'] ]); //获取首个列表


        $data = [
            'one_sort' => $one_sort,
            'two_sort' => $two_sort,
            'building' => $buildings
        ];
        if( empty($buildings) )
        {
            $data['building'] = false;
        }
        return show(true, 'ok' , $data);
    }


    //根据一一级分类获取二级分类。
    public function getTwoSort($id)
    {
        (new IDMustBePositiveInt())->goCheck();
        $two_sort = Db::table('building_column')->where([ 'pid'=> $id])->order(['order'=>'asc'])->select();//获取二级分类
        return show(true, 'ok' , $two_sort);
    }
}